### ISSUE TITLE
undefined variable while submitting subscription form

### ISSUE THREAD

**Issue by alwex** [silverstripe-archive/silverstripe-newsletter#117]
Hi,
I am using silverstripe 3.4.x with this module. 
everything work fine except when I try to submit the subscription form with empty fields, the call to `addErrorMessage($fieldName, $message, $messageType, $escapeHtml = true)` is not correct and the argument `$messageType` is missing.

```
[Warning] Missing argument 3 for Form::addErrorMessage(), called in /var/www/project/newsletter/code/pagetypes/SubscriptionPage.php on line 421 and defined
```

**Comment by dhensby** [comment]
Thanks for taking the time to post to our issue tracker.

This repository is in the SilverStripe Archive which means it's a module we no longer actively support.

We're looking more to the community to provide support for these modules if users want to continue to use them.

Would you be willing to spend the time submitting a patch for this issue?

**Comment by alwex** [comment]
Hi, no problem.

I have submitted a pull request, do you mind accepting it in order to make it available to others?
thank you.

https://github.com/silverstripe-archive/silverstripe-newsletter/pull/118

**Comment by dhensby** [comment]
done
