### ISSUE TITLE
Sent emails just have 'HTMLtext' in the body

### ISSUE THREAD

**Issue by borriej** [silverstripe-archive/silverstripe-newsletter#12]
Using SS 3.03

Sent emails just have 'HTMLtext' in the body

subject is correct, but the body is only showing 'HTMLText'
## UPDATE:

Noticed that if i replace $Body for \ $Body i do get content.. maybe update this build?
This is not handy if we have to use \ 
## UPDATE

After adding a new template, selecting it, sending it.. same problems occurs..

**Comment by wilr** [comment]
Tested again for v2, works fine.
