### ISSUE TITLE
Silverstripe 4 Support

### ISSUE THREAD

**Issue by EurSylvain** [silverstripe-archive/silverstripe-newsletter#126]
Good morning,

I have seen that you started to port this module to Silverstripe 4.X in 2018. However nothing as moved since. I've tried to install the developpment version on a test website, but there are still a lot of errors...Do you plan to finish the port or is this module abandonned?

This is important for me as I have a bunch of Silverstripe 3.X website that await this module to be upgraded to Silverstripe 4.

Thank you very much!

**Comment by wilr** [comment]
Hi @EurSylvain 

I've moved on from maintaining the website which used Newsletter but as far as I was aware it worked as intended (albeit that would have been on SilverStripe 4.0 rather than 4.4). Please detail any issues on the repo as issues and I can investigate further.

Cheers

**Comment by EurSylvain** [comment]
Hi,
I'm happy to help and glad that this project is still on (very useful!). I will open some new issues as asked.

Cheers
