### ISSUE TITLE
Include reCAPTCHA

### ISSUE THREAD

**Issue by palomamtnez** [silverstripe-archive/silverstripe-newsletter#137]
Is there a way to protect the newsletter form from bots?
What about including reCAPTCHA or a technique as honeypot?

**Comment by wilr** [comment]
You can use https://github.com/UndefinedOffset/silverstripe-nocaptcha. I've added the hook in https://github.com/silverstripe-archive/silverstripe-newsletter/commit/f6be67bc8682b487da9796447fbadf7c5765cf57
