### ISSUE TITLE
Verification should be done for each mailing list subscription not per recipient

### ISSUE THREAD

**Issue by miiihi** [silverstripe-archive/silverstripe-newsletter#16]
Hi,

first, great, that you are upgrading newsletter module. It was long overdue...

But, as I'm browsing thru the code, I found a conceptual problem. Verification of subscriptions has to be done for each mailing list (or rather batch of subscriptions done in the same request) not per recipient, as it is now. Consider following scenario in the current implementation:
- user subscribes to mailing list A
- user confirm subscription to mailing list A
- recipient is now verified
- user (or anybody) subscribes to mailing list B
- confirmation mail is sent, but as recipient is already verified, it is irrelevant! recipient is immediately subscribed to mailing list B

Do you see the problem?

I can offer some help with implementation of the fix, if needed...

Best regards, miiihi

**Comment by wilr** [comment]
Closing as this is > 5 years old without any progress. Please reopen if code can be provided.

Cheers
