### ISSUE TITLE
can't save draft(s) or saving hangs: Refused to set unsafe header "Connection"

### ISSUE THREAD

**Issue by borriej** [silverstripe-archive/silverstripe-newsletter#20]
My Setup:
- SS 2.4.9
- Brache 0.5 (from today)

Steps:
- Installed, dev/build?flush=all
- added security groups
- Tab:Newsletter
- Add new type & draft
- type text in the concept message (draft)
- hit save

Result:
- The button goes to "saving..."
- Button never changes, it just displays "saving...."
- No CMS feedback/message of a failure or succes
- page is never saved, or at least no feedback of save

Google Chrome console error:
- Refused to set unsafe header "Connection"

**Comment by wilr** [comment]
Tested in v4, draft saves fine.
