### ISSUE TITLE
NewsletterAdmin::$template_paths Ignored

### ISSUE THREAD

**Issue by ss23** [silverstripe-archive/silverstripe-newsletter#32]
From http://open.silverstripe.org/ticket/6305

NewsletterAdmin::$template_paths in the configuration file is ignored when previewing or sending the email: Resulting in a template not found error.

The template is found when configuring the newsletter type, but not when actually using it. Then the template must reside in mysite/templates/email/!

---

Additional comments found on open.silverstripe.org

**Comment by wilr** [comment]
Fixed in v2 with preview (both email and desktop previews).
