### ISSUE TITLE
Refactor how the Unsubscribe "page" is accessed

### ISSUE THREAD

**Issue by ss23** [silverstripe-archive/silverstripe-newsletter#35]
From http://open.silverstripe.org/ticket/2459

$UnsubscribeLink should return the link, not the entire <a> element.

Unsubscribe_Controller extends Page_Controller, this should also have an Unsubscribe extends Page data record, so it can be in the CMS. Otherwise, we're relying on hacks to fake a data record. It also means you can customise the Unsubscribe page in the CMS!

See r53210 on why this is a bad approach, to have a controller without a data record.

Finally, $UnsubscribeLink should do a DataObject::get_one('UnsubscribePage') to find out the link. This is similar to how we discover the CheckoutPage record in the ecommerce module!

@halkyon

**Comment by wilr** [comment]
Fixed in v2,
