### ISSUE TITLE
Anchors are processed incorrectly.

### ISSUE THREAD

**Issue by ss23** [silverstripe-archive/silverstripe-newsletter#39]
From http://open.silverstripe.org/ticket/4247

The newsletter module appears to process anchors incorrectly. If I create an anchor the link is replaced to be the full path. This means my email has links back to the website in it.

For example `<a href="#link">Anchor link</a><a name="link"></a>` turns into `<a href=" http://example.com/admin/newsletter/#link">Anchor link</a><a name="link"></a>`

This breaks any table of contents one might have in a newsletter.

I am using SilverStripe 2.3.1 and Newsletter module 0.1.1

**Comment by wilr** [comment]
Fixed, anchors are ignored in v2 (b69dc04)
