### ISSUE TITLE
ComplexTableField doesn't work in the newsletter module

### ISSUE THREAD

**Issue by ss23** [silverstripe-archive/silverstripe-newsletter#41]
From http://open.silverstripe.org/ticket/4501

For those of us looking to changing/customising the newsletter module it's a major issue that none of the relationship table fields work in the newsletter module.

When opening a popup from one of these a message appears in the popup saying that the class can't handle a sub-URL from the newsletterAdmin object.

---

Attached File: http://open.silverstripe.org/attachment/ticket/4501/newsletter.rar

**Comment by wilr** [comment]
Closing as CTF
