### ISSUE TITLE
Fatal error in CMS

### ISSUE THREAD

**Issue by bumbus** [silverstripe-archive/silverstripe-newsletter#58]
Hi folks,
unfortunatly i get this error:
Fatal error: Call to a member function setTitle() on a non-object in .../newsletter/code/form/gridfield/NewsletterGridFieldDetailForm.php on line 23

when i want to open newsletter in cms. 

Any ideas how to fix this.

Regards
Bumbus

**Comment by wilr** [comment]
See fix on #89
