### ISSUE TITLE
exclude can't be called on an UnsavedRelationList

### ISSUE THREAD

**Issue by jimt** [silverstripe-archive/silverstripe-newsletter#67]
After updating from SilverStripe 3.0 to 3.1.3, and the newsletter module to trunk [77d916e29](https://github.com/silverstripe-labs/silverstripe-newsletter/commit/77d916e29bbbb9a92cf77af5a62dbd4bad6a0e8d) I get an error when I visit the admin/newsletter/MailingList page:

```
Error at framework/model/UnsavedRelationList.php line 315: Uncaught LogicException: exclude can't be called on an UnsavedRelationList.
```

I can eliminate the error (and some of the functionality :-/ ) by changing the value returned by:

``` php
        /**
         * Returns all recipients who aren't blacklisted, and are verified.
         */
        public function ActiveRecipients() {
                return $this->Recipients()->exclude('Blacklisted', 1)->exclude('Verified', 0);
        }
```

to simply:

``` php
                return $this->Recipients();
```

**Comment by wilr** [comment]
Fixed in ab2de6fb
