### ISSUE TITLE
"Save as new..." breaks tracking links

### ISSUE THREAD

**Issue by jimt** [silverstripe-archive/silverstripe-newsletter#68]
If you:
- visit _Sent Newsletters_
- select one that had a link to a page in the site, and click _Save as new..._
- send it again

The tracking links generated when the new copy is sent are broken. They contain the string _newsletterlinks_ twice, e.g. `http://example.com/newsletterlinksnewsletterlinks/hextrackinghashishere`

(And for what its worth, removing one 'newsletterlinks' and attempting to visit the resulting URL does not succeed either, suggesting the hash is bogus.)

**Comment by wilr** [comment]
Fixed in `2.0` 4044072ceea079d560a659f1e9f6a4fc26c55ed3
