### ISSUE TITLE
Tracking links break embedded image URLs

### ISSUE THREAD

**Issue by jimt** [silverstripe-archive/silverstripe-newsletter#69]
If you use TinyMCE to embed an image in a newsletter, it will work fine for the test email, but when you send the email to one of the lists and the URLs are rewritten for tracking, you end up with an img src URL like:

`http://example.com/assetsnewsletterlinks/99fcc43a64aaa84c0d2309c5ea76b30fUploadsnewsletterlinks/99fcc43a64aaa84c0d2309c5ea76b30fMy-Image.png`

**Comment by wilr** [comment]
Regex is set to only rewrite a href rather than any URL in v2. Please reopen if still an issue on new release.
