### ISSUE TITLE
Recipient counts are incorrect

### ISSUE THREAD

**Issue by RantyDave** [silverstripe-archive/silverstripe-newsletter#93]
A list with one recipient is listed as having none.

![silverstripe_-_newsletter](https://cloud.githubusercontent.com/assets/4230547/7790134/e16a52c6-02cf-11e5-9122-e78a04621a76.png)

**Comment by wilr** [comment]
This number shows active, verified recipients rather than all the recipients (i.e a user has not verified their account). I've added the word 'active' to that so it now reads 0 active recipients.
